### ISSUE TITLE
OGP追加

### ISSUE THREAD

**Issue by longtime1116** [longtime1116/github_gardener#31]
https://cont-hub.com/knowledge/glossary/ogp/

**Comment by hoshinaoshi** [comment]
og:imageについて、SVGだとうまく表示できないようなので、pngにする必要があります。

外部サイトですが、これを使うと

* サクッとpngを取得できる
* URLが固定となる

ので、一旦これで作るのはいかがでしょうか？
https://grass-graph.moshimo.works/images/hoshinaoshi.png

**Comment by longtime1116** [comment]
これめっちゃいいですね！！！
ありがとうございます。
実装する時はこれを使いたい！

**Comment by longtime1116** [comment]
#55 で新たに issue 追加してこっちは close
