### ISSUE TITLE
fetch元の庭と表示されている庭が違う

### ISSUE THREAD

**Issue by longtime1116** [longtime1116/github_gardener#56]
https://github.com/users/longtime1116/contributions/

と

https://github-gardener.herokuapp.com/longtime1116

timezone 違いのせい？とおもってオハイオのAZで EC2 を立ててそこから curl で叩いてみたら、github-gardener と同じ結果が表示されてしまった。

うーん、ブラウザから見ると変わるのはなんなんだ。。。

**Comment by hoshinaoshi** [comment]
@masa-laughndie の8/3の芝が枯れていることについて調査しました。

# 原因
原因は、private repositoryに対するコミットの庭判定だと思われます。

# 根拠
@masa-laughndie の庭の芝枯れた日(8/3)のコミットの状況をみると、
private repositoryにのみcommitされた4 activityが8/3のコミット状況でした。
これについて、該当のprivate repositoryに閲覧権限があるアカウントでgithubにログインした状態とログアウトした状態(完全に外から見た状態)で比較をしてみました。

その結果、当たり前ではありますが、
## ログイン時に見た状態
![fireshot capture 68 - masa-laughndie - https___github com_masa-laughndie](https://user-images.githubusercontent.com/5182986/43903565-b50b276a-9c27-11e8-9e6b-2d2f5c19b9d0.png)

## ログアウト時に見た状態
![fireshot capture 67 - masa-laughndie github - https___github com_masa-laughndie](https://user-images.githubusercontent.com/5182986/43903618-cdd60f76-9c27-11e8-9ffb-826c1b09e388.png)

ここから言えることは、APIを叩く時に、githubに対して認証が通っているか否かによって、庭の見え方が異なると言えると思います。

そのため下記が成り立った場合、
* https://github.com/users/masa-laughndie/contributions/ を直接叩いた時
  * (a)ログインしている: private repositoryに対するcommitが草となって見える
  * (b)ログインしていない: private repositoryに対するcommitが草となって見えない

本アプリから見えている庭(app.rb#115で取得した庭)は、(b)と同義であるため、@masa-laughndie の8/3の芝が枯れているのではないかと思います。

## 検証
### ログイン状態
<img width="712" alt="2018-08-09 23 06 58" src="https://user-images.githubusercontent.com/5182986/43904378-71155ed4-9c29-11e8-8d36-09790623f7a2.png">

### ログアウト状態
<img width="693" alt="2018-08-09 23 06 30" src="https://user-images.githubusercontent.com/5182986/43904355-63150578-9c29-11e8-9d1d-9df92b57524f.png">

上記より、private repositoryにcommitされたか否かに対して、該当private repositoryの閲覧権限があるかどうかにより、庭の見え方が異なると言えます。

@masa-laughndie の8/3の芝が枯れていることに対しては、private repositoryのコミットを庭に反映させるかどうかの設定により、復旧ができるかどうかが変わると思われます。また、その設定によりアプリの側としての対応が変わると思います。

以上、調査結果の共有です。

**Comment by longtime1116** [comment]
問題解決能力の高さ、感服しました…！！
高橋さんの設定が private 非表示設定なのではないかなと予想します。
(私はprivateも表示設定にしてるのですが、200日以上の草の継続が完全にpublicだけで今までやってこれたとは考えづらく、private表示設定にすればこの問題は起きないのではという予感があります。)

**Comment by hoshinaoshi** [comment]
> 高橋さんの設定が private 非表示設定なのではないかなと予想します。

自分もどの時点からか、private onlyでやっているも草が生え続けているので、完全にコレですね！
一件落着🚀

**Comment by longtime1116** [comment]
高橋さんは public only だったのが原因でした。
今では public and private で表示しているので、草が2018年8月10日現在、58日継続しています！
https://github-gardener.herokuapp.com/masa-laughndie
