### ISSUE TITLE
/:name/by_yearページにおいて、過去の庭が現在の年の庭で表示されてしまう。

### ISSUE THREAD

**Issue by hoshinaoshi** [longtime1116/github_gardener#63]
# 概要
タイトルの通り、全ての年で同じ庭が表示されてしまう。

# 予想している原因
query stringでしていしている`{from: yyyy-mm-dd}`が効かなくなったのかもしれません

# スクリーンショット
![fireshot capture 76 - github-gardener - https___github-gardener herokuapp com_longtime1116_by_year](https://user-images.githubusercontent.com/5182986/46903357-a1739b00-cf0e-11e8-9d67-4b8f6f24cdca.png)

**Comment by longtime1116** [comment]
報告ありがとうございます

クエリが↓のとおりだったので、修正します。
ダメ: `from: 2017-1-1`
OK: `from: 2017-01-01`

https://github.com/longtime1116/github_gardener/pull/64
